name = "vocab-app"
main = ".open-next/worker.js"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "0stack.org", custom_domain = true }
]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
